/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#07006c",
        "tertiary-container": "#00a572",
        "on-secondary-container": "#b0b2ff",
        "primary-fixed-dim": "#ffb3af",
        "surface-container": "#1d1f26",
        "surface-variant": "#33343b",
        "background": "#111319",
        "primary-container": "#ff5357",
        "on-tertiary-fixed": "#002113",
        "surface": "#111319",
        "surface-bright": "#373940",
        "inverse-on-surface": "#2e3037",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed": "#410006",
        "outline": "#b08784",
        "surface-tint": "#ffb3af",
        "on-primary": "#68000e",
        "error": "#ffb4ab",
        "on-background": "#e2e2ea",
        "surface-dim": "#111319",
        "surface-container-low": "#191b22",
        "inverse-primary": "#bf0024",
        "on-primary-container": "#5c000b",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#c0c1ff",
        "tertiary": "#4edea3",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#003824",
        "on-secondary": "#1000a9",
        "primary": "#ffb3af",
        "secondary-container": "#3131c0",
        "on-primary-fixed-variant": "#930019",
        "on-tertiary-container": "#00311f",
        "on-surface": "#e2e2ea",
        "surface-container-high": "#282a30",
        "inverse-surface": "#e2e2ea",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-container-highest": "#33343b",
        "primary-fixed": "#ffdad8",
        "on-surface-variant": "#e9bcb9",
        "error-container": "#93000a",
        "secondary-fixed": "#e1e0ff",
        "on-error": "#690005",
        "outline-variant": "#5f3e3d",
        "surface-container-lowest": "#0c0e14",
        "tertiary-fixed-dim": "#4edea3",
        "secondary": "#c0c1ff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        "margin-desktop": "2rem",
        "margin-tablet": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "code-sm": ["Inter", "monospace"]
      }
    },
  },
  plugins: [],
}
